In [16]:
import torch

text_y = torch.reshape(torch.arange(16),(2, 4, 2))
meta = torch.reshape(torch.arange(8),(2, 4))

In [66]:
speech_len = 10
dim = 2
text_upsampling_list = []

for sentence, sentence_meta in zip(text_y, meta):
    sentence_upsampling = torch.cat(
        [token_.repeat(meta_,1) for token_ ,meta_ in zip(sentence, sentence_meta)], dim=0
    )
    print(sentence_upsampling.shape)
    if len(sentence_upsampling) < speech_len:
        sentence_upsampling = torch.cat(
            [sentence_upsampling, sentence_upsampling.new_zeros(speech_len - len(sentence_upsampling), dim)], dim=0
        ).unsqueeze(0)
    else:
        sentence_upsampling = sentence_upsampling[:speech_len].unsqueeze(0)
    print(sentence_upsampling.shape)
    text_upsampling_list.append(sentence_upsampling)
        

text_upsampling = torch.cat(text_upsampling_list, dim=0)
print(text_upsampling.shape)

torch.Size([6, 2])
torch.Size([1, 10, 2])
torch.Size([22, 2])
torch.Size([1, 10, 2])
torch.Size([2, 10, 2])


In [29]:
for sentence, sentence_meta in zip(text_y, meta):
    for token_ ,meta_ in zip(sentence, sentence_meta):
        print(token_, meta_)

tensor([0, 1]) tensor(0)
tensor([2, 3]) tensor(1)
tensor([4, 5]) tensor(2)
tensor([6, 7]) tensor(3)
tensor([8, 9]) tensor(4)
tensor([10, 11]) tensor(5)
tensor([12, 13]) tensor(6)
tensor([14, 15]) tensor(7)


In [49]:
text_upsampling

tensor([[ 2,  3],
        [ 4,  5],
        [ 4,  5],
        [ 6,  7],
        [ 6,  7],
        [ 6,  7],
        [ 8,  9],
        [ 8,  9],
        [ 8,  9],
        [ 8,  9],
        [10, 11],
        [10, 11],
        [10, 11],
        [10, 11],
        [10, 11],
        [12, 13],
        [12, 13],
        [12, 13],
        [12, 13],
        [12, 13],
        [12, 13],
        [14, 15],
        [14, 15],
        [14, 15],
        [14, 15],
        [14, 15],
        [14, 15],
        [14, 15]])